version: '3.8'

services:
  postgres:
    image: postgis/postgis:14-master
    container_name: postgres_dev
    restart: always
    environment:
      - POSTGRES_PASSWORD=ficticio
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongo:
    image: mongo:6.0
    container_name: mongo_dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ficticio
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  postgres_data:
